### ISSUE TITLE
Build error when building edh tooling

### ISSUE THREAD

**Issue by cdfa** [complyue/tour#3]
I get the following error from build edh tooling in the gitpod workspace:
```
edh                  > /workspace/edh-universe/e-wrks/edh/host.hs/src/Language/Edh/Batteries.hs:166:13: error:
edh                  >     • No instance for (Catch.MonadCatch (Haskeline.InputT IO))
edh                  >         arising from a use of ‘Catch.catch’
edh                  >     • In the expression: Catch.catch (readLines initialLines)
edh                  >       In the expression:
edh                  >         Catch.catch (readLines initialLines)
edh                  >           $ \case
edh                  >               UserInterrupt -> startOver
edh                  >               ex -> throw ex
edh                  >       In an equation for ‘readInput’:
edh                  >           readInput !ps1 !ps2 !initialLines
edh                  >             = Catch.catch (readLines initialLines)
edh                  >                 $ \case
edh                  >                     UserInterrupt -> startOver
edh                  >                     ex -> throw ex
edh                  >             where
edh                  >                 startOver
edh                  >                   = Catch.catch (readLines [])
edh                  >                       $ \case
edh                  >                           UserInterrupt -> startOver
edh                  >                           ex -> throw ex
edh                  >                 parsePasteSpec :: Parsec Void Text (Int, Int, Text)
edh                  >                 parsePasteSpec
edh                  >                   = do space
edh                  >                        ....
edh                  >                 recvPaste :: Text -> Haskeline.InputT IO (Maybe EdhInput)
edh                  >                 ....
edh                  >     |
edh                  > 166 |             Catch.catch (readLines initialLines) $ \case
edh                  >     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
edh                  > 
edh                  > /workspace/edh-universe/e-wrks/edh/host.hs/src/Language/Edh/Batteries.hs:170:27: error:
edh                  >     • No instance for (Catch.MonadCatch (Haskeline.InputT IO))
edh                  >         arising from a use of ‘Catch.catch’
edh                  >     • In the expression: Catch.catch (readLines [])
edh                  >       In the expression:
edh                  >         Catch.catch (readLines [])
edh                  >           $ \case
edh                  >               UserInterrupt -> startOver
edh                  >               ex -> throw ex
edh                  >       In an equation for ‘startOver’:
edh                  >           startOver
edh                  >             = Catch.catch (readLines [])
edh                  >                 $ \case
edh                  >                     UserInterrupt -> startOver
edh                  >                     ex -> throw ex
edh                  >     |
edh                  > 170 |               startOver = Catch.catch (readLines []) $ \case
edh                  >     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by complyue** [comment]
Root cause is some pkg has been updated to work with stackage lts 21.25, but the gitpod env stays at lts 16.31.

Updated the gitpod stuff, but blocked by https://github.com/gitpod-io/gitpod/issues/19615 so far.

**Comment by complyue** [comment]
Fixed by #4 , thanks to @axonasif !
